all:
  children:
    dns_clients:
      hosts:
        ca:
          ansible_host: 192.168.1.105
          ansible_user: debian
        vault:
          ansible_host: 192.168.1.104
          ansible_user: debian
        openldap:
          ansible_host: 192.168.1.103
          ansible_user: debian
        ubuntu-gui:
          ansible_host: 192.168.1.101
          ansible_user: alex

    dns_server:
      hosts:
        dns-1:
          ansible_host: 192.168.1.106
          ansible_user: debian

    ldap_servers:
      hosts:
        openldap:
          ansible_host: 192.168.1.103
          ansible_user: debian   # même machine que dns_clients.openldap (192.168.1.103) ; vars héritées de là-bas

    openbao_server:
      hosts:
        vault:
          ansible_host: 192.168.1.104
          ansible_user: debian

    pfsense:
      hosts:
        192.168.1.1: {}
